### ISSUE TITLE
🐛 Mixed up report comment when running in a matrix

### ISSUE THREAD

**Issue by rcrowe** [moonrepo/run-report-action#12]
I'm running a matrix of Moon runners `index: [0, 1, 2, 3]` with the report job configured for a matrix:

```yaml
- name: "Generate Moon report"
  uses: moonrepo/run-report-action@v1
  if: success() || failure()
  with:
    access-token: ${{ secrets.GITHUB_TOKEN }}
    matrix: ${{ toJSON(matrix) }}
```

These are the outputs:

**Index 1:**
- auth/graphql:generate
- auth/graphql:lint

<img width="550" alt="Screenshot 2024-03-28 at 20 39 34" src="https://github.com/moonrepo/run-report-action/assets/282571/98afb7e9-2907-4c39-aeee-3a1e90e2e8ec">

**Index 2:**
- auth/graphql:test
- auth/jwk-publisher:lint

<img width="533" alt="Screenshot 2024-03-28 at 20 39 58" src="https://github.com/moonrepo/run-report-action/assets/282571/007e8cdc-79ae-47d2-bd12-f183070d7460">

However, when the reports are generated you can see they are mixed up with unexpected results in both:

<img width="927" alt="Screenshot 2024-03-28 at 20 38 48" src="https://github.com/moonrepo/run-report-action/assets/282571/5765fc46-1932-46f6-836d-82a5b4d39031">
